# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 366ce349a3141022debc2a51bd3e57a5efb64b97fa7debcc77742c6a95ae9e2853d65e9d6d0368f73f13d7a6c38198db240ade1377915a41f3eed447ca0a551b

test:
  secret_key_base: 660723e634ce795423b7fe9585a904cef2056333568bed999578bd827e863f8ccc5981408bd89fd8d6aca388f6dff32c3b0c6beb8ecd76008ae42ed36aa38ac1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
